### ISSUE TITLE
How can I see detailed arguments?

### ISSUE THREAD

**Issue by ACmagic** [aaa4xu/pubg-lobby-proxy#1]
A millions thanks for your great work. 
Can you please advise how I can see detailed arguments instead of "Object"?

**Comment by aaa4xu** [comment]
Sorry, cant understand your question. Could you please rephrase it? Where are you see "Object"?

**Comment by ACmagic** [comment]
Silly me. Easy to achieve what I want by wrapping the request with JSON.Stringify()...many thanks
