### ISSUE TITLE
PUBG does not connect

### ISSUE THREAD

**Issue by Avnsx** [aaa4xu/pubg-lobby-proxy#14]
Hey, when adding 
```
127.0.0.1 prod-live-front.playbattlegrounds.com
127.0.0.1 pctest-live-front.playbattlegrounds.com
```
to the windows hosts file. PUBG no longer manages to connect to the lobby and all that I see in npm running through cmd, is a single asset request calling "favicon" while your code says "Connection to game server dont exists"

How do I fix this?

**Comment by aaa4xu** [comment]
Sorry, but this project is abandoned many years ago. Most likely pubg changed its api or introduce ssl pinning in that time.
