### ISSUE TITLE
Can we monitor in-game traffic?

### ISSUE THREAD

**Issue by ACmagic** [aaa4xu/pubg-lobby-proxy#2]
Can we monitor in-game traffic? Especially the match result, i.e, the kill count of each player.

**Comment by aaa4xu** [comment]
Nope, only lobby. PUBG use unreal engine network protocol in match and very difficult to parse it without game itself

**Comment by Boxroom** [comment]
but how do they get their 'per game' data?
https://pubg.op.gg/user/WALLZ2?server=na

**Comment by aaa4xu** [comment]
They have deal with Bluehole. Looks like now they have access to some private api.

> But today, we are very excited to tell you guys that we are building a website for Battlegrounds! As of yesterday, we've signed a MOU with Bluehole to cooperate closely about data & statistics.
[Source](https://www.reddit.com/r/PUBATTLEGROUNDS/comments/6qy0tn/opgg_we_need_your_help/)
