### ISSUE TITLE
How Post params work?

### ISSUE THREAD

**Issue by myserywork** [aaa4xu/pubg-lobby-proxy#5]
Packet sent by game : 

![image](https://user-images.githubusercontent.com/11938133/33676499-05c8dbf4-da9d-11e7-978c-3f7c63abcd50.png)

Packet sent manually on Postman

![image](https://user-images.githubusercontent.com/11938133/33676582-3ec9c378-da9d-11e7-8043-8abc468ae00c.png)

getting : 
`{
    "success": false,
    "error": "Timeout"
}`

How to send that packet:?

**Comment by aaa4xu** [comment]
Do you used `GET` method in Postman 😄

**Comment by myserywork** [comment]
Yes... it was just a test same error ocours, how to send that packet via post?

**Comment by myserywork** [comment]
![image](https://user-images.githubusercontent.com/11938133/33676847-02317162-da9e-11e7-84b9-06b3221f40a5.png)

**Comment by myserywork** [comment]
![image](https://user-images.githubusercontent.com/11938133/33677056-aebfefe4-da9e-11e7-9257-7ad61379b119.png)

full url

**Comment by aaa4xu** [comment]
Pull latest revision and use `GET` `http://localhost:8000/api/CustomGameApi/customgame@CustomGameApi@GetCustomGameState/?type=2` for your request

**Comment by aaa4xu** [comment]
Im make mistake. Correct version:
<img width="506" alt="chrome_2017-12-06_21-21-34" src="https://user-images.githubusercontent.com/1071970/33677948-7e51cd0a-dacb-11e7-9eb8-e8d798d860ba.png">

**Comment by myserywork** [comment]
@aaa4xu it worked for 1 post param what if i need to ban a user

The packet should be : 


[10000013,null,"CustomGameApi","customgame@CustomGameApi@BanUser","account.2eb5cdb325c6434d9db5500a01758cb2"]

and when i send 
![image](https://user-images.githubusercontent.com/11938133/33680498-eee59e20-daa8-11e7-9c3f-1012d62d89d8.png)

**Comment by aaa4xu** [comment]
Try like that:
`POST` `http://localhost:8000/api/CustomGameApi/customgame@CustomGameApi@BanUser/`
`{
	"type": 2,
	"arguments": [
		"account.2eb5cdb325c6434d9db5500a01758cb2"
	]
}`

**Comment by myserywork** [comment]
@aaa4xu  its for use with the current version?

**Comment by aaa4xu** [comment]
Yeap

**Comment by myserywork** [comment]
![image](https://user-images.githubusercontent.com/11938133/33680999-7307b584-daaa-11e7-825f-dc2f03f41169.png)

well i've updated when you said.. and now i have back to the current code it stoped working

**Comment by myserywork** [comment]
![image](https://user-images.githubusercontent.com/11938133/33681308-46467f5c-daab-11e7-9ac5-501e430585c0.png)
same for ban

**Comment by aaa4xu** [comment]
Check one more time: 
<img width="454" alt="chrome_2017-12-06_22-53-47" src="https://user-images.githubusercontent.com/1071970/33682429-7b66eafa-dad8-11e7-826e-54c2411fd1ed.png">

**Comment by myserywork** [comment]
It Worked!. do you have skype or discord?

**Comment by aaa4xu** [comment]
Discord: aaa4xu#2877

**Comment by ACmagic** [comment]
what is "type: 2" ? Do i need to add "type : 2" to every api?
