### ISSUE TITLE
what is "type:2" in request body?

### ISSUE THREAD

**Issue by ACmagic** [aaa4xu/pubg-lobby-proxy#6]
In [issue 5](https://github.com/aaa4xu/pubg-lobby-proxy/issues/5),  i found u put "type: 2" in the request body, what is "type: 2"?

**Comment by aaa4xu** [comment]
`type` used for set PUBG message type:
0: Events. Using 0 for all requests/responses `callbackId`:
```
PubgResponse {
  callbackId: 0,
  flags: null,
  interface: 'ClientApi',
  method: 'Invalidate',
  arguments: [ 'client.game', null, null ]
}
```

1: Normal (default). Using 10000+ `callbackId`:
```
PubgRequest {
     callbackId: 10007,
     flags: null,
     interface: 'UserProxyApi',
     method: 'GetOpenGameInfo',
     arguments: []
}
```

2: "Bypass". Using for **CustomGameApi** (only?). Using 10000000+ `callbackId`:
```
PubgRequest {
     callbackId: 10000001,
     flags: null,
     interface: 'CustomGameApi',
     method: 'customgame@CustomGameApi@GetCustomGameList',
     arguments: []
}
```
