### ISSUE TITLE
UserAllRecord from PUBG Websocket

### ISSUE THREAD

**Issue by NeOMakinG** [aaa4xu/pubg-lobby-proxy#7]
It looks like this request isn't working anymore, what's up from the PUBG servers ?

**Comment by aaa4xu** [comment]
I think this method was replaced by `GetUserAllRecord`. But, it require one argument and i dont known what it want.

**Comment by NeOMakinG** [comment]
Trying to use it with accountid and it refuse it, Also tried with some others argument (steamid, account name...)

Still returning a "NullReferenceException"
